# This rule is not used by the project log-analyzer-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to aiops.aiops.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: log-analyzer-operator
    app.kubernetes.io/managed-by: kustomize
  name: loganalysisrequest-viewer-role
rules:
- apiGroups:
  - aiops.aiops.dev
  resources:
  - loganalysisrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aiops.aiops.dev
  resources:
  - loganalysisrequests/status
  verbs:
  - get
