---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - aiops.aiops.dev
  resources:
  - loganalysisrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aiops.aiops.dev
  resources:
  - loganalysisrequests/finalizers
  verbs:
  - update
- apiGroups:
  - aiops.aiops.dev
  resources:
  - loganalysisrequests/status
  verbs:
  - get
  - patch
  - update
